# Generated by Django 2.2.7 on 2019-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=300)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=300)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('url_image', models.CharField(max_length=500)),
            ],
        ),
    ]
